version: "3.8"
services:
  pub:
    container_name: pub
    image: 'node:16-alpine'
    working_dir: /app
    command: sh -c "sleep 5 && npm i -f && npm run start:pub"
    volumes:
      - $PWD:/app
    depends_on:
      - redis
    ports:
      - 3000:3000
  sub:
    container_name: sub
    image: 'node:16-alpine'
    working_dir: /app
    command: sh -c "sleep 5 && npm i -f && npm run start:sub"
    volumes:
      - $PWD:/app
    depends_on:
      - redis
  redis:
    container_name: redis
    image: 'redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    logging:
      driver: none
networks:
  default:
      driver: bridge